[workspace]
authors = ["Dan Allan <>"]
channels = ["conda-forge"]
name = "10 tricks"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "~=3.12"

[pypi-dependencies]
tiled = { git = "https://github.com/genematx/tiled.git", branch="fix-download", extras=["client"]}
bluesky-tiled-plugins = ">=2.0.1,<3"
ipykernel = ">=7.1.0,<8"
bluesky = ">=1.14.6,<2"
ophyd = ">=1.11.0,<2"
numpy = ">=2.3.5,<3"
matplotlib = ">=3.10.8,<4"
ipympl = ">=0.10.0,<0.11"
